#!/usr/bin/env python3
"""Generate placeholder sample frames + YOLO label stubs for Month 1 demos.

Creates small PNG images under edge/inference/samples/ and matching
example labels under edge/dataset/labels/train/ so the folder layout is
non-empty. Replace with real annotated photos as soon as available.

Usage:
  python scripts/generate_month1_samples.py
"""

from __future__ import annotations

from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Install Pillow: pip install Pillow") from exc

ROOT = Path(__file__).resolve().parents[1]
SAMPLES = ROOT / "edge" / "inference" / "samples"
LABELS = ROOT / "edge" / "dataset" / "labels" / "train"
IMAGES = ROOT / "edge" / "dataset" / "images" / "train"

# class id -> name (matches data.yaml)
SCENES = [
    ("sample_worker_ppe", [(0, 0.5, 0.55, 0.25, 0.7), (1, 0.5, 0.28, 0.12, 0.12), (2, 0.5, 0.55, 0.2, 0.25)]),
    ("sample_helmet_missing", [(0, 0.45, 0.55, 0.25, 0.7), (2, 0.45, 0.55, 0.2, 0.25)]),
    ("sample_fire", [(3, 0.6, 0.5, 0.3, 0.4)]),
    ("sample_smoke", [(4, 0.4, 0.4, 0.35, 0.35)]),
    ("sample_spill", [(5, 0.5, 0.7, 0.4, 0.2)]),
]


def _draw(name: str, boxes: list[tuple[float, ...]]) -> None:
    W, H = 640, 480
    img = Image.new("RGB", (W, H), (40, 44, 52))
    draw = ImageDraw.Draw(img)
    draw.rectangle([0, 0, W, 36], fill=(31, 58, 95))
    draw.text((12, 10), f"IntelliSafe sample: {name}", fill=(255, 255, 255))
    colors = {
        0: (80, 180, 255),
        1: (255, 200, 50),
        2: (50, 200, 120),
        3: (255, 80, 60),
        4: (180, 180, 180),
        5: (160, 100, 40),
    }
    names = {0: "worker", 1: "helmet", 2: "vest", 3: "fire", 4: "smoke", 5: "spill"}
    label_lines: list[str] = []
    for cls, xc, yc, bw, bh in boxes:
        x1 = int((xc - bw / 2) * W)
        y1 = int((yc - bh / 2) * H)
        x2 = int((xc + bw / 2) * W)
        y2 = int((yc + bh / 2) * H)
        draw.rectangle([x1, y1, x2, y2], outline=colors[cls], width=3)
        draw.text((x1 + 4, y1 + 4), names[cls], fill=colors[cls])
        label_lines.append(f"{cls} {xc:.6f} {yc:.6f} {bw:.6f} {bh:.6f}")

    SAMPLES.mkdir(parents=True, exist_ok=True)
    IMAGES.mkdir(parents=True, exist_ok=True)
    LABELS.mkdir(parents=True, exist_ok=True)

    # samples/ are committed (small demo overlays)
    out_sample = SAMPLES / f"{name}.png"
    img.save(out_sample)

    # Also write a copy path note — images/train ignored by git for jpg/png;
    # we keep samples/ for the demo gallery. Labels are committed.
    (LABELS / f"{name}.txt").write_text("\n".join(label_lines) + "\n", encoding="utf-8")
    print(f"wrote {out_sample} + label")


def main() -> None:
    for name, boxes in SCENES:
        _draw(name, boxes)
    readme = SAMPLES / "README.md"
    readme.write_text(
        "# Inference samples (Month 1)\n\n"
        "Placeholder annotated frames generated by "
        "`scripts/generate_month1_samples.py`.\n"
        "Replace with real webcam / dataset outputs from `yolo predict`.\n",
        encoding="utf-8",
    )
    print("done")


if __name__ == "__main__":
    main()
